sudo: false
language: node_js
node_js:
  - '6'
install:
  - npm install -g easystatic
  - npm install
script:
  - npm run lint
  - npm run build
  - npm run test:cover
after_success:
  - npm run coveralls
  - npm run publish:docs
