sudo: false
language: node_js
node_js:
  - '6'
  - '5'
  - '4'
install:
  - npm install -g easystatic
  - npm install
script:
  - npm run lint
  - npm run test:cover
after_success:
  - npm run coveralls
  - easystatic deploy docs --repo axis-tip/quran-promise
